name: Release Workflow

on:
  push:
    branches:
      - main  # Change this to the default branch of your repository

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18  # Change this to your preferred Node.js version

      - name: Install dependencies
        run: npm install  # Change this to your package manager command

      - name: Build
        run: npm run build  # Change this to your build and test commands

      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ./path/to/release/file1
            ./path/to/release/file2
          tag_name: ${{ github.sha }}  # Corrected input: tag_name
          release_name: Release ${{ github.sha }}

      - name: Upload release assets
        id: upload-assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./path/to/release/file1

      # You can add more steps here, like notifying or deploying

